// The OpenNext handler is generated by `npm run build:cloudflare`.
// @ts-ignore generated build artifact; unavailable before the OpenNext build.
import { default as nextHandler } from "./.open-next/worker.js";

type D1Statement = {
  bind: (...values: unknown[]) => { run: () => Promise<unknown> };
};

type ScheduledWorkerEnv = {
  DB: {
    prepare: (query: string) => D1Statement;
  };
};

/**
 * Custom OpenNext Worker entrypoint.
 *
 * `fetch` remains owned by the generated OpenNext adapter. The scheduled
 * handler is intentionally limited to low-risk D1 maintenance so the app can
 * later add queue consumers or Durable Objects without replacing its web
 * request handler again.
 */
export default {
  fetch: nextHandler.fetch,

  async scheduled(_controller: unknown, env: ScheduledWorkerEnv) {
    const now = new Date().toISOString();
    await env.DB.prepare(
      "DELETE FROM google_oauth_state WHERE expires_at <= ?",
    )
      .bind(now)
      .run();
  },
};
