ALTER TYPE "recalc_admin"."BusinessEventType" ADD VALUE IF NOT EXISTS 'EXTENSION_TOKEN_ISSUED';
ALTER TYPE "recalc_admin"."BusinessEventType" ADD VALUE IF NOT EXISTS 'EXTENSION_RUN_CREATED';
ALTER TYPE "recalc_admin"."BusinessEventType" ADD VALUE IF NOT EXISTS 'EXTENSION_RUN_EVENT';
ALTER TYPE "recalc_admin"."BusinessEventType" ADD VALUE IF NOT EXISTS 'WHATSAPP_WEB_OPENED';
